package com.buildbot.contactsmanagement.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * This class represents a user in the system.
 *
 * @Entity indicates that this class is a JPA entity and maps to a database table.
 */
@Entity
@Data
@AllArgsConstructor
@RequiredArgsConstructor
@Table(name = "users")
public class User extends BaseEntity {

    /**
     * The unique identifier for the user (auto-generated by the database).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer userId;

    /**
     * The username of the user, which is unique and non-nullable.
     */
    @Column(name = "user_name", nullable = false, unique = true)
    private String userName;

    /**
     * The first name of the user, which is non-nullable.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * The last name of the user (optional).
     */
    @Column(name = "last_name")
    private String lastName;

    /**
     * The email address of the user, which is unique and non-nullable.
     */
    @Column(name = "email", unique = true)
    private String email;

    /**
     * The password of the user, which is non-nullable.
     * **Security Consideration:** The password should be stored securely using a one-way hashing algorithm (e.g., BCrypt). Never store plain text passwords!
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * The user's roles in the system (comma-separated or JSON format, depending on implementation).
     */
    @Column(name = "roles")
    private String roles;

}